---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
- name: centos-6.10
- name: centos-7.8
- name: centos-8.2
- name: debian-8.8
- name: debian-9.12
- name: debian-10.4
- name: ubuntu-16.04
- name: ubuntu-18.04
- name: ubuntu-20.04

suites:
  - name: default
    run_list:
      - recipe[sshd-test::default]

  - name: sshd_config
    run_list:
      - recipe[sshd-test::default]
    attributes:
      sshd:
        sshd_config:
          ServerKeyBits: 2048
          ListenAddress: 0.0.0.0
          PasswordAuthentication: 'no'
