---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
- name: ubuntu-18.04
- name: ubuntu-16.04
- name: ubuntu-14.04
- name: debian-8.5
- name: debian-9.0
- name: centos-7.2
- name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[sshd-test::default]

  - name: sshd_config
    run_list:
      - recipe[sshd-test::default]
    attributes:
      sshd:
        sshd_config:
          ServerKeyBits: 2048
          ListenAddress: 0.0.0.0
          PasswordAuthentication: 'no'
