Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - spec/**/*

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

CaseIndentation:
  EnforcedStyle: end

MethodLength:
  Max: 50

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

SpaceBeforeFirstArg:
  Enabled: false

AbcSize:
  Enabled: false

# In the case of libraries/helpers.rb, parallel assignment just looks so much nicer
ParallelAssignment:
  Enabled: false
