sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk
rvm:
  - 2.5.0
script:
  - bundle exec rubocop
  - bundle exec foodcritic -f any .
  - bundle exec rspec
